### ISSUE TITLE
jQuery.filer adds "[]" to the name parameter of input

### ISSUE THREAD

**Issue by jhudaverdi** [CreativeDream/jQuery.filer#117]
jQuery.filer adds "[]" to the name parameter of input and that causing not being able to get this parameter in the Controller of ASP.NET MVC5. For more information please visit: [Multiple File Uploads in ASP.NET MVC using View Models](http://stackoverflow.com/questions/39930119/multiple-file-uploads-in-asp-net-mvc-using-view-models/39931778#39931778). Thanks...

**Comment by benpoulson** [comment]
Without having any ASP.NET knowledge; isn't this because jQuery.filer is sending over an array of files?

**Comment by jhudaverdi** [comment]
No, it is due to adding "[]" to the end of the name parameter in the js file even if I use "files[]" as parameter.

**Comment by CreativeDream** [comment]
@jhudaverdi have you found the solution?

**Comment by armartinez** [comment]
Hi I'm having the same issue and the only solution is creating a custom model binder, but it's much more preferable that the "[]" it's not added to the name automatically, @CreativeDream I think it would be best if this choice is left to the user instead of forced upon, or at least give an option to prevent this.

**Comment by CreativeDream** [comment]
@armartinez thanks. I will fix it in the next version.

**Comment by luisasalas** [comment]
$("#NAME_OF_INPUT_ID").attr("name", "file");

**Comment by CreativeDream** [comment]
@luisasalas good ideea

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
